function HadCRUT = s1a1preparehadcrutmonthly(filePath)
%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/teda/Drive/Research/Data/HadCrut/HadCRUT.4.6.0.0.monthly_ns_avg.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/10/17 16:39:45

%% Initialize variables.
filename = filePath;

%% Format for each line of text:
%   column1: datetimes (%{yyyy/MM}D)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%7{yyyy/MM}D%9f%9f%9f%9f%9f%9f%9f%9f%9f%9f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'EmptyValue', NaN,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
HadCRUT = table(dataArray{1:end-1}, 'VariableNames', {'date','medianT','VarName3','VarName4','VarName5','VarName6','VarName7','VarName8','VarName9','VarName10','VarName11','VarName12'});
HadCRUT = HadCRUT(:,{'date','medianT'});
% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% HadCRUT.date=datenum(HadCRUT.date);

end