% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/teda/Drive/Research/Data/HadCrut/HadCRUT3v-gl.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/06/19 15:27:08

% Initialize variables.
filename = '../Data/Temperature/Time_series/HadCRUT3v-gl.txt';
delimiter = ' ';
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';
fileID = fopen(filename,'r');
dataArray = ...
    textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne',...
    true, 'TextType', 'string', 'EmptyValue', NaN,  'ReturnOnError', false);
fclose(fileID);
hadCRUT3 = [dataArray{1:end-1}];

%Imported numeric matrix has the following format:
% for year = 1850 to endyear
%   format(i5,13f7.3) year, 12 * monthly values, annual value
%   format(i5,12i7) year, 12 * percentage coverage of hemisphere or globe 
%Remove the rows for percent coverage
iV = ~isnan(hadCRUT3(:,end));
hadCRUT3 = hadCRUT3(iV,:);
ind = 1;
for ii = 1:size(hadCRUT3,1)    
    for iM = 1:12
        yrH(ind) = hadCRUT3(ii,1); % record the year
        mthH(ind) = iM; %record the month
        yrFH(ind) = yrH(ind) + (iM-1)/12; %fractional year
        TH(ind) = hadCRUT3(ii,iM+1); %record the monthly T anomaly
        ind = ind+1;
    end   
end
TH = TH'; yrH = yrH'; yrFH = yrFH'; mthH = mthH';
% Clear temporary variables:
clearvars filename delimiter formatSpec fileID dataArray ans;